language: node_js
sudo: false
node_js:
  - '4.4'
  - '5.6'
  - '6.1'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'mangony' ]; then cd .. && eval "mv $currentfolder mangony" && cd mangony; fi

git:
  submodules: false
# whitelist
branches:
  only:
    - master
    - dev